connection:
  info:
    #ip: 127.0.0.1
    ip: 51.124.219.98
    port: 5000
    tls_config:
      enable: false
  name: FlaskConnection
  path: ibmfl.connection.flask_connection
  sync: false
data:
  info:
    host: phr-icufair-central-db-server.postgres.database.azure.com
    port: 5432
    database: aggregator
    envPath: ./examples/PHR/aggregator/.env
  name: PostgreSqlDataHandler
  path: examples.PHR.data.postgresql_data_handler
fusion:
  name: ConcatFusionHandler
  path: examples.PHR.aggregator.fusion.concat_fusion_handler
hyperparams:
  global:
    num_parties: 2
    rounds: 1
  local:
    training:
      epochs: 1
protocol_handler:
  name: ProtoHandler
  path: ibmfl.aggregator.protohandler.proto_handler
