aggregator:
  ip: 127.0.0.1
  port: 5000
connection:
  info:
    ip: 127.0.0.1
    port: 8085
    tls_config:
      enable: false
  name: FlaskConnection
  path: ibmfl.connection.flask_connection
  sync: false
data:
  info:
    host: edit-ph-eicu.postgres.database.azure.com
    port: 5432
    database: hospital2
  name: PostgreSqlDataHandler
  path: examples.PHR.data.postgresql_data_handler
local_training:
  name: LocalTrainingHandler
  path: examples.PHR.party.training.local_training_handler
model:
  name: HelloWorld
  path: examples.PHR.HelloWorld
  spec:
    model_definition: examples/configs/PHR/script/compiled_keras.h5
    model_name: HelloWorld
privacy:
  metrics: true
protocol_handler:
  name: PartyProtocolHandler
  path: ibmfl.party.party_protocol_handler
