version: "3"

services:
  postgres:
    image: postgres:11-alpine
    volumes:
      - .volumes/psql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: aggregator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
